// Code generated by github.com/izumin5210/gex. DO NOT EDIT.

// +build tools

package tools

// tool dependencies
import (
	_ "github.com/go-task/task/v3/cmd/task"
	_ "github.com/google/wire/cmd/wire"
	_ "github.com/vektah/dataloaden"
)

// If you want to use tools, please run the following command:
//  go generate ./tools.go
//
//go:generate go build -v -o=./bin/task github.com/go-task/task/v3/cmd/task
//go:generate go build -v -o=./bin/wire github.com/google/wire/cmd/wire
//go:generate go build -v -o=./bin/dataloaden github.com/vektah/dataloaden
