// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: protogql/graphql.proto

package protogql_pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GraphqlSchemaOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypePrefix string `protobuf:"bytes,1,opt,name=type_prefix,json=typePrefix,proto3" json:"type_prefix,omitempty"`
}

func (x *GraphqlSchemaOptions) Reset() {
	*x = GraphqlSchemaOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protogql_graphql_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphqlSchemaOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphqlSchemaOptions) ProtoMessage() {}

func (x *GraphqlSchemaOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protogql_graphql_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphqlSchemaOptions.ProtoReflect.Descriptor instead.
func (*GraphqlSchemaOptions) Descriptor() ([]byte, []int) {
	return file_protogql_graphql_proto_rawDescGZIP(), []int{0}
}

func (x *GraphqlSchemaOptions) GetTypePrefix() string {
	if x != nil {
		return x.TypePrefix
	}
	return ""
}

var file_protogql_graphql_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*GraphqlSchemaOptions)(nil),
		Field:         2056,
		Name:          "protogql.schema",
		Tag:           "bytes,2056,opt,name=schema",
		Filename:      "protogql/graphql.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional protogql.GraphqlSchemaOptions schema = 2056;
	E_Schema = &file_protogql_graphql_proto_extTypes[0]
)

var File_protogql_graphql_proto protoreflect.FileDescriptor

var file_protogql_graphql_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x71, 0x6c, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68,
	0x71, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67,
	0x71, 0x6c, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x14, 0x47, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x0b,
	0x74, 0x79, 0x70, 0x65, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x74, 0x79, 0x70, 0x65, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x3a, 0x55, 0x0a,
	0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x88, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x67, 0x71, 0x6c, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x06, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x69, 0x7a, 0x75, 0x6d, 0x69, 0x6e, 0x35, 0x32, 0x31, 0x30, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x67, 0x71, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x71, 0x6c, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x71,
	0x6c, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protogql_graphql_proto_rawDescOnce sync.Once
	file_protogql_graphql_proto_rawDescData = file_protogql_graphql_proto_rawDesc
)

func file_protogql_graphql_proto_rawDescGZIP() []byte {
	file_protogql_graphql_proto_rawDescOnce.Do(func() {
		file_protogql_graphql_proto_rawDescData = protoimpl.X.CompressGZIP(file_protogql_graphql_proto_rawDescData)
	})
	return file_protogql_graphql_proto_rawDescData
}

var file_protogql_graphql_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protogql_graphql_proto_goTypes = []interface{}{
	(*GraphqlSchemaOptions)(nil),     // 0: protogql.GraphqlSchemaOptions
	(*descriptorpb.FileOptions)(nil), // 1: google.protobuf.FileOptions
}
var file_protogql_graphql_proto_depIdxs = []int32{
	1, // 0: protogql.schema:extendee -> google.protobuf.FileOptions
	0, // 1: protogql.schema:type_name -> protogql.GraphqlSchemaOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protogql_graphql_proto_init() }
func file_protogql_graphql_proto_init() {
	if File_protogql_graphql_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protogql_graphql_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphqlSchemaOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protogql_graphql_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_protogql_graphql_proto_goTypes,
		DependencyIndexes: file_protogql_graphql_proto_depIdxs,
		MessageInfos:      file_protogql_graphql_proto_msgTypes,
		ExtensionInfos:    file_protogql_graphql_proto_extTypes,
	}.Build()
	File_protogql_graphql_proto = out.File
	file_protogql_graphql_proto_rawDesc = nil
	file_protogql_graphql_proto_goTypes = nil
	file_protogql_graphql_proto_depIdxs = nil
}
