package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.

import (
	"context"
	"testapp/graph"
	"testapp/model"
)

func (r *queryResolver) Entries(ctx context.Context) ([]*model.Entry, error) {
	// This function body is generated by github.com/izumin5210/remixer. DO NOT EDIT.

	resp, err := (&queryProtoResolver{Resolver: r.Resolver}).Entries(ctx)
	if err != nil {
		return nil, err
	}
	return model.EntryListFromRepeatedProto(resp), nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

