// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTaskInput struct {
	Title string `json:"title"`
}

type CreateTaskPayload struct {
	Task *Task `json:"task"`
}

