package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.

import (
	"context"
	"testapp/graph"
	"testapp/model"
)

func (r *mutationResolver) CreateTask(ctx context.Context, input *model.CreateTaskInput) (*model.CreateTaskPayload, error) {
	// This function body is generated by github.com/izumin5210/remixer. DO NOT EDIT.

	resp, err := (&mutationProtoResolver{Resolver: r.Resolver}).CreateTask(ctx, input)
	if err != nil {
		return nil, err
	}
	return model.CreateTaskPayloadFromProto(resp), nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }

