// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateHelloInput struct {
	Message string `json:"message"`
}

type CreateHelloPayload struct {
	Hello *Hello `json:"hello"`
}

type HelloByUserEdge struct {
	Node   *Hello `json:"node"`
	Cursor string `json:"cursor"`
}

type HellosByUserConnection struct {
	TotalCount int                             `json:"totalCount"`
	Edges      []*HelloByUserEdge              `json:"edges"`
	Nodes      []*Hello                        `json:"nodes"`
	PageInfo   *HellosByUserConnectionPageInfo `json:"pageInfo"`
}

type HellosByUserConnectionPageInfo struct {
	EndCursor   string `json:"endCursor"`
	HasNextPage bool   `json:"hasNextPage"`
}

