// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package resolver

import (
	"testapp/graph"
)

// User returns graph.UserResolver implementation.
func (r *Resolver) User() graph.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }

