// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	wktypes_pb "apis/go/wktypes"

	"github.com/golang/protobuf/ptypes/timestamp"
	"github.com/golang/protobuf/ptypes/wrappers"
)

type Hello struct {
	Timestamp   *timestamp.Timestamp
	Int32Value  *wrappers.Int32Value
	Int64Value  *wrappers.Int64Value
	Uint32Value *wrappers.UInt32Value
	Uint64Value *wrappers.UInt64Value
	FloatValue  *wrappers.FloatValue
	DoubleValue *wrappers.DoubleValue
	BoolValue   *wrappers.BoolValue
	StringValue *wrappers.StringValue
}

func HelloListFromRepeatedProto(in []*wktypes_pb.Hello) []*Hello {
	out := make([]*Hello, len(in))
	for i, m := range in {
		out[i] = HelloFromProto(m)
	}
	return out
}

func HelloFromProto(in *wktypes_pb.Hello) *Hello {
	out := &Hello{
		Timestamp:   in.GetTimestamp(),
		Int32Value:  in.GetInt32Value(),
		Int64Value:  in.GetInt64Value(),
		Uint32Value: in.GetUint32Value(),
		Uint64Value: in.GetUint64Value(),
		FloatValue:  in.GetFloatValue(),
		DoubleValue: in.GetDoubleValue(),
		BoolValue:   in.GetBoolValue(),
		StringValue: in.GetStringValue(),
	}

	return out
}

func HelloListToRepeatedProto(in []*Hello) []*wktypes_pb.Hello {
	out := make([]*wktypes_pb.Hello, len(in))
	for i, m := range in {
		out[i] = HelloToProto(m)
	}
	return out
}

func HelloToProto(in *Hello) *wktypes_pb.Hello {
	out := &wktypes_pb.Hello{
		Timestamp:   in.Timestamp,
		Int32Value:  in.Int32Value,
		Int64Value:  in.Int64Value,
		Uint32Value: in.Uint32Value,
		Uint64Value: in.Uint64Value,
		FloatValue:  in.FloatValue,
		DoubleValue: in.DoubleValue,
		BoolValue:   in.BoolValue,
		StringValue: in.StringValue,
	}

	return out
}

type HelloInput struct {
	Timestamp   *timestamp.Timestamp
	Int32Value  *wrappers.Int32Value
	Int64Value  *wrappers.Int64Value
	Uint32Value *wrappers.UInt32Value
	Uint64Value *wrappers.UInt64Value
	FloatValue  *wrappers.FloatValue
	DoubleValue *wrappers.DoubleValue
	BoolValue   *wrappers.BoolValue
	StringValue *wrappers.StringValue
}

func HelloInputListFromRepeatedProto(in []*wktypes_pb.Hello) []*HelloInput {
	out := make([]*HelloInput, len(in))
	for i, m := range in {
		out[i] = HelloInputFromProto(m)
	}
	return out
}

func HelloInputFromProto(in *wktypes_pb.Hello) *HelloInput {
	out := &HelloInput{
		Timestamp:   in.GetTimestamp(),
		Int32Value:  in.GetInt32Value(),
		Int64Value:  in.GetInt64Value(),
		Uint32Value: in.GetUint32Value(),
		Uint64Value: in.GetUint64Value(),
		FloatValue:  in.GetFloatValue(),
		DoubleValue: in.GetDoubleValue(),
		BoolValue:   in.GetBoolValue(),
		StringValue: in.GetStringValue(),
	}

	return out
}

func HelloInputListToRepeatedProto(in []*HelloInput) []*wktypes_pb.Hello {
	out := make([]*wktypes_pb.Hello, len(in))
	for i, m := range in {
		out[i] = HelloInputToProto(m)
	}
	return out
}

func HelloInputToProto(in *HelloInput) *wktypes_pb.Hello {
	out := &wktypes_pb.Hello{
		Timestamp:   in.Timestamp,
		Int32Value:  in.Int32Value,
		Int64Value:  in.Int64Value,
		Uint32Value: in.Uint32Value,
		Uint64Value: in.Uint64Value,
		FloatValue:  in.FloatValue,
		DoubleValue: in.DoubleValue,
		BoolValue:   in.BoolValue,
		StringValue: in.StringValue,
	}

	return out
}

