// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package resolver

import (
	"context"
	"testapp/graph"
	"testapp/model"
)

func (a *queryProtoResolverAdapter) Tasks(ctx context.Context) ([]*model.Task, error) {
	resp, err := a.protoResolver.Tasks(ctx)
	if err != nil {
		return nil, err
	}
	return model.TaskListFromRepeatedProto(resp), nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver {
	return &queryProtoResolverAdapter{&queryProtoResolver{r}}
}

type queryProtoResolverAdapter struct{ protoResolver *queryProtoResolver }

