// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
}

type UserError interface {
	IsUserError()
}

type CreateHelloInput struct {
	Message string `json:"message"`
}

type CreateHelloPayload struct {
	Success *CreateHelloSuccess `json:"success"`
	Errors  []UserError         `json:"errors"`
}

type CreateHelloSuccess struct {
	Hello *Hello `json:"hello"`
}

type HelloMessageInvalid struct {
	Hello   *Hello   `json:"hello"`
	Message string   `json:"message"`
	Path    []string `json:"path"`
}

func (HelloMessageInvalid) IsUserError() {}

type UserNotFound struct {
	Message string   `json:"message"`
	Path    []string `json:"path"`
}

func (UserNotFound) IsUserError() {}

