// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: comments/comments.proto

package comments_pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// CommentEnum leading line 1
//
// CommentEnum leading line 2
type CommentEnum int32

const (
	CommentEnum_COMMENT_ENUM_UNSPECIFIED CommentEnum = 0
	// FOO leading line 1
	// FOO leading line 2
	CommentEnum_FOO CommentEnum = 1 // FOO trailing
	// Bar leading
	CommentEnum_BAR CommentEnum = 2
)

// Enum value maps for CommentEnum.
var (
	CommentEnum_name = map[int32]string{
		0: "COMMENT_ENUM_UNSPECIFIED",
		1: "FOO",
		2: "BAR",
	}
	CommentEnum_value = map[string]int32{
		"COMMENT_ENUM_UNSPECIFIED": 0,
		"FOO":                      1,
		"BAR":                      2,
	}
)

func (x CommentEnum) Enum() *CommentEnum {
	p := new(CommentEnum)
	*p = x
	return p
}

func (x CommentEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommentEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_comments_comments_proto_enumTypes[0].Descriptor()
}

func (CommentEnum) Type() protoreflect.EnumType {
	return &file_comments_comments_proto_enumTypes[0]
}

func (x CommentEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommentEnum.Descriptor instead.
func (CommentEnum) EnumDescriptor() ([]byte, []int) {
	return file_comments_comments_proto_rawDescGZIP(), []int{0}
}

// ParentMessage Leading Comment Line 1
// ParentMessage Leading Comment Line 2
//
// ParentMessage Leading Comment Line 3
type ParentMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ParentMessage id leading line 1
	// ParentMessage id leading line 2
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // ParentMessage id trailing comment
	// ParentMessage body leading comment
	Body string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"` // ParentMessage body trailing comment
	// ParentMessage comment_enum leading comment
	CommentEnum CommentEnum `protobuf:"varint,3,opt,name=comment_enum,json=commentEnum,proto3,enum=testapi.comments.CommentEnum" json:"comment_enum,omitempty"`
	// ParentMessage nested leading comment
	Nested *ParentMessage_NestedMessage `protobuf:"bytes,4,opt,name=nested,proto3" json:"nested,omitempty"`
}

func (x *ParentMessage) Reset() {
	*x = ParentMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comments_comments_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentMessage) ProtoMessage() {}

func (x *ParentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_comments_comments_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentMessage.ProtoReflect.Descriptor instead.
func (*ParentMessage) Descriptor() ([]byte, []int) {
	return file_comments_comments_proto_rawDescGZIP(), []int{0}
}

func (x *ParentMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ParentMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ParentMessage) GetCommentEnum() CommentEnum {
	if x != nil {
		return x.CommentEnum
	}
	return CommentEnum_COMMENT_ENUM_UNSPECIFIED
}

func (x *ParentMessage) GetNested() *ParentMessage_NestedMessage {
	if x != nil {
		return x.Nested
	}
	return nil
}

// NestedMessage Leading line 1
//
// NestedMessage Leading line 2
type ParentMessage_NestedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// NestedMessage body leading comment
	NestedBody string `protobuf:"bytes,1,opt,name=nested_body,json=nestedBody,proto3" json:"nested_body,omitempty"` // NestedMessage body trailing comment
}

func (x *ParentMessage_NestedMessage) Reset() {
	*x = ParentMessage_NestedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comments_comments_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParentMessage_NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentMessage_NestedMessage) ProtoMessage() {}

func (x *ParentMessage_NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_comments_comments_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentMessage_NestedMessage.ProtoReflect.Descriptor instead.
func (*ParentMessage_NestedMessage) Descriptor() ([]byte, []int) {
	return file_comments_comments_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ParentMessage_NestedMessage) GetNestedBody() string {
	if x != nil {
		return x.NestedBody
	}
	return ""
}

var File_comments_comments_proto protoreflect.FileDescriptor

var file_comments_comments_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x74, 0x65, 0x73, 0x74, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0xee, 0x01, 0x0a, 0x0d,
	0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x12, 0x40, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x65, 0x6e, 0x75,
	0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x45,
	0x6e, 0x75, 0x6d, 0x12, 0x45, 0x0a, 0x06, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x06, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x1a, 0x30, 0x0a, 0x0d, 0x4e, 0x65,
	0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6e,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x2a, 0x3d, 0x0a, 0x0b,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x1c, 0x0a, 0x18, 0x43,
	0x4f, 0x4d, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x46, 0x4f, 0x4f,
	0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x41, 0x52, 0x10, 0x02, 0x42, 0x1e, 0x5a, 0x1c, 0x61,
	0x70, 0x69, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x3b,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_comments_comments_proto_rawDescOnce sync.Once
	file_comments_comments_proto_rawDescData = file_comments_comments_proto_rawDesc
)

func file_comments_comments_proto_rawDescGZIP() []byte {
	file_comments_comments_proto_rawDescOnce.Do(func() {
		file_comments_comments_proto_rawDescData = protoimpl.X.CompressGZIP(file_comments_comments_proto_rawDescData)
	})
	return file_comments_comments_proto_rawDescData
}

var file_comments_comments_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_comments_comments_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_comments_comments_proto_goTypes = []interface{}{
	(CommentEnum)(0),                    // 0: testapi.comments.CommentEnum
	(*ParentMessage)(nil),               // 1: testapi.comments.ParentMessage
	(*ParentMessage_NestedMessage)(nil), // 2: testapi.comments.ParentMessage.NestedMessage
}
var file_comments_comments_proto_depIdxs = []int32{
	0, // 0: testapi.comments.ParentMessage.comment_enum:type_name -> testapi.comments.CommentEnum
	2, // 1: testapi.comments.ParentMessage.nested:type_name -> testapi.comments.ParentMessage.NestedMessage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_comments_comments_proto_init() }
func file_comments_comments_proto_init() {
	if File_comments_comments_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_comments_comments_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParentMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comments_comments_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParentMessage_NestedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_comments_comments_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_comments_comments_proto_goTypes,
		DependencyIndexes: file_comments_comments_proto_depIdxs,
		EnumInfos:         file_comments_comments_proto_enumTypes,
		MessageInfos:      file_comments_comments_proto_msgTypes,
	}.Build()
	File_comments_comments_proto = out.File
	file_comments_comments_proto_rawDesc = nil
	file_comments_comments_proto_goTypes = nil
	file_comments_comments_proto_depIdxs = nil
}
