schema {
	query: Query
	mutation: Mutation
}
directive @grpc(service: String!, rpc: String!) on FIELD_DEFINITION
directive @protobuf(type: String!) on OBJECT | ENUM | INPUT_OBJECT
input FollowUserInput @protobuf(type: ".testdata.FollowUserRequest") {
	userId: String!
	friendId: String!
}
enum Role @protobuf(type: ".testdata.User.Role") {
	ROLE_UNSPECIFIED
	ADMIN
}
input UnfollowUserInput @protobuf(type: ".testdata.UnfollowUserRequest") {
	userId: String!
	friendId: String!
}
type User @protobuf(type: ".testdata.User") {
	id: String!
	fullName: String!
	followeeUserIds: [String!]!
	followerUserIds: [String!]!
	role: Role!
}
type Query {
	users(pageToken: String!, pageSize: Int!): [User!]! @grpc(service: ".testdata.UserService", rpc: "ListUsers")
}
type Mutation {
	followUser(input: FollowUserInput!): Boolean @grpc(service: ".testdata.UserService", rpc: "FollowUser")
	unfollowUser(input: UnfollowUserInput!): Boolean @grpc(service: ".testdata.UserService", rpc: "UnfollowUser")
}

