schema {
	query: Query
	mutation: Mutation
}
input FollowUserRequest {
	userId: String!
	friendId: String!
}
enum Role {
	ROLE_UNSPECIFIED
	ADMIN
}
input UnfollowUserRequest {
	userId: String!
	friendId: String!
}
type User {
	id: String!
	fullName: String!
	followeeUserIds: [String!]!
	followerUserIds: [String!]!
	role: Role!
}
type Query {
	users(page_token: String!, page_size: Int!): [User!]!
}
type Mutation {
	followUser(input: FollowUserInput!): Boolean
	unfollowUser(input: UnfollowUserInput!): Boolean
}

