type BatchGetUsersRequest @protobuf(type: "testdata.BatchGetUsersRequest") {
	userIds: [String!]!
}
input BatchGetUsersRequestInput @protobuf(type: "testdata.BatchGetUsersRequest") {
	userIds: [String!]!
}
type BatchGetUsersResponse @protobuf(type: "testdata.BatchGetUsersResponse") {
	users: [User!]!
}
input BatchGetUsersResponseInput @protobuf(type: "testdata.BatchGetUsersResponse") {
	users: [UserInput!]!
}
type User @protobuf(type: "testdata.User") {
	id: String!
	fullName: String!
	followeeUserIds: [String!]!
	followerUserIds: [String!]!
	role: UserRole!
}
input UserInput @protobuf(type: "testdata.User") {
	id: String!
	fullName: String!
	followeeUserIds: [String!]!
	followerUserIds: [String!]!
	role: UserRole!
}
enum UserRole @protobuf(type: "testdata.User.Role") {
	ROLE_UNSPECIFIED
	ADMIN
}

