// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"testdata/task/api"
)

type Task struct {
	ID uint64

	Title string

	Status *TaskStatus

	AssigneeIds []uint64

	Assignees []*User
}

func TaskListFromRepeatedProto(in []*api.Task) []*Task {
	out := make([]*Task, len(in))
	for i, m := range in {
		out[i] = TaskFromProto(m)
	}
	return out
}

func TaskFromProto(in *api.Task) *Task {
	return &Task{

		ID: in.Id,

		Title: in.Title,

		Status: TaskStatusFromProto(in.Status),

		AssigneeIds: in.AssigneeIds,
	}
}

func TaskListToRepeatedProto(in []*Task) []*api.Task {
	out := make([]*api.Task, len(in))
	for i, m := range in {
		out[i] = TaskToProto(m)
	}
	return out
}

func TaskToProto(in *Task) *api.Task {
	return &api.Task{

		Id: in.ID,

		Title: in.Title,

		Status: TaskStatusToProto(in.Status),

		AssigneeIds: in.AssigneeIds,
	}
}

type TaskInput struct {
	ID uint64

	Title string

	Status *TaskStatus

	AssigneeIds []uint64
}

func TaskInputListFromRepeatedProto(in []*api.Task) []*TaskInput {
	out := make([]*TaskInput, len(in))
	for i, m := range in {
		out[i] = TaskInputFromProto(m)
	}
	return out
}

func TaskInputFromProto(in *api.Task) *TaskInput {
	return &TaskInput{

		ID: in.Id,

		Title: in.Title,

		Status: TaskStatusFromProto(in.Status),

		AssigneeIds: in.AssigneeIds,
	}
}

func TaskInputListToRepeatedProto(in []*TaskInput) []*api.Task {
	out := make([]*api.Task, len(in))
	for i, m := range in {
		out[i] = TaskInputToProto(m)
	}
	return out
}

func TaskInputToProto(in *TaskInput) *api.Task {
	return &api.Task{

		Id: in.ID,

		Title: in.Title,

		Status: TaskStatusToProto(in.Status),

		AssigneeIds: in.AssigneeIds,
	}
}

type User struct {
	ID uint64

	FullName string

	Role *UserRole
}

func UserListFromRepeatedProto(in []*api.User) []*User {
	out := make([]*User, len(in))
	for i, m := range in {
		out[i] = UserFromProto(m)
	}
	return out
}

func UserFromProto(in *api.User) *User {
	return &User{

		ID: in.Id,

		FullName: in.FullName,

		Role: UserRoleFromProto(in.Role),
	}
}

func UserListToRepeatedProto(in []*User) []*api.User {
	out := make([]*api.User, len(in))
	for i, m := range in {
		out[i] = UserToProto(m)
	}
	return out
}

func UserToProto(in *User) *api.User {
	return &api.User{

		Id: in.ID,

		FullName: in.FullName,

		Role: UserRoleToProto(in.Role),
	}
}

type UserInput struct {
	ID uint64

	FullName string

	Role *UserRole
}

func UserInputListFromRepeatedProto(in []*api.User) []*UserInput {
	out := make([]*UserInput, len(in))
	for i, m := range in {
		out[i] = UserInputFromProto(m)
	}
	return out
}

func UserInputFromProto(in *api.User) *UserInput {
	return &UserInput{

		ID: in.Id,

		FullName: in.FullName,

		Role: UserRoleFromProto(in.Role),
	}
}

func UserInputListToRepeatedProto(in []*UserInput) []*api.User {
	out := make([]*api.User, len(in))
	for i, m := range in {
		out[i] = UserInputToProto(m)
	}
	return out
}

func UserInputToProto(in *UserInput) *api.User {
	return &api.User{

		Id: in.ID,

		FullName: in.FullName,

		Role: UserRoleToProto(in.Role),
	}
}

type TaskStatus struct {
	Proto api.Task_Status
}

func TaskStatusListFromRepeatedProto(in []api.Task_Status) []*TaskStatus {
	out := make([]*TaskStatus, len(in))
	for i, m := range in {
		out[i] = TaskStatusFromProto(m)
	}
	return out
}

func TaskStatusFromProto(in api.Task_Status) *TaskStatus {
	return &TaskStatus{Proto: in}
}

func TaskStatusListToRepeatedProto(in []*TaskStatus) []api.Task_Status {
	out := make([]api.Task_Status, len(in))
	for i, m := range in {
		out[i] = TaskStatusToProto(m)
	}
	return out
}

func TaskStatusToProto(in *TaskStatus) api.Task_Status {
	return in.Proto
}

func (e TaskStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.Proto.String()))
}

func (e *TaskStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	e.Proto = api.Task_Status(api.Task_Status_value[str])
	return nil
}

type UserRole struct {
	Proto api.User_Role
}

func UserRoleListFromRepeatedProto(in []api.User_Role) []*UserRole {
	out := make([]*UserRole, len(in))
	for i, m := range in {
		out[i] = UserRoleFromProto(m)
	}
	return out
}

func UserRoleFromProto(in api.User_Role) *UserRole {
	return &UserRole{Proto: in}
}

func UserRoleListToRepeatedProto(in []*UserRole) []api.User_Role {
	out := make([]api.User_Role, len(in))
	for i, m := range in {
		out[i] = UserRoleToProto(m)
	}
	return out
}

func UserRoleToProto(in *UserRole) api.User_Role {
	return in.Proto
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.Proto.String()))
}

func (e *UserRole) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	e.Proto = api.User_Role(api.User_Role_value[str])
	return nil
}
