// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTaskInput struct {
	Task *TaskInput `json:"task"`
}

type CreateTaskPayload struct {
	Task *Task `json:"task"`
}

type ProtoOneof struct {
	Fields []*ProtoOneofField `json:"fields"`
}

type ProtoOneofField struct {
	Name   string `json:"name"`
	GoName string `json:"goName"`
}
