// Code generated by github.com/izumin5210/gex. DO NOT EDIT.

// +build tools

package tools

// tool dependencies
import (
	_ "github.com/99designs/gqlgen"
	_ "github.com/izumin5210/remixer/cmd/protoc-gen-graphql"
)

// If you want to use tools, please run the following command:
//  go generate ./tools.go
//
//go:generate go build -v -o=./bin/gqlgen github.com/99designs/gqlgen
//go:generate go build -v -o=./bin/gqlgen github.com/izumin5210/cmd/protoc-gen-graphql
