// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: graphql.proto

package options

import (
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GraphqlQueryOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Output string `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *GraphqlQueryOptions) Reset() {
	*x = GraphqlQueryOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphqlQueryOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphqlQueryOptions) ProtoMessage() {}

func (x *GraphqlQueryOptions) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphqlQueryOptions.ProtoReflect.Descriptor instead.
func (*GraphqlQueryOptions) Descriptor() ([]byte, []int) {
	return file_graphql_proto_rawDescGZIP(), []int{0}
}

func (x *GraphqlQueryOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GraphqlQueryOptions) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type GraphqlMutationOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GraphqlMutationOptions) Reset() {
	*x = GraphqlMutationOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphqlMutationOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphqlMutationOptions) ProtoMessage() {}

func (x *GraphqlMutationOptions) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphqlMutationOptions.ProtoReflect.Descriptor instead.
func (*GraphqlMutationOptions) Descriptor() ([]byte, []int) {
	return file_graphql_proto_rawDescGZIP(), []int{1}
}

func (x *GraphqlMutationOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GraphqlFieldOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id bool `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GraphqlFieldOptions) Reset() {
	*x = GraphqlFieldOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphqlFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphqlFieldOptions) ProtoMessage() {}

func (x *GraphqlFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphqlFieldOptions.ProtoReflect.Descriptor instead.
func (*GraphqlFieldOptions) Descriptor() ([]byte, []int) {
	return file_graphql_proto_rawDescGZIP(), []int{2}
}

func (x *GraphqlFieldOptions) GetId() bool {
	if x != nil {
		return x.Id
	}
	return false
}

type GraphqlMessageOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DelegateTo string `protobuf:"bytes,1,opt,name=delegate_to,json=delegateTo,proto3" json:"delegate_to,omitempty"`
}

func (x *GraphqlMessageOptions) Reset() {
	*x = GraphqlMessageOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphqlMessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphqlMessageOptions) ProtoMessage() {}

func (x *GraphqlMessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphqlMessageOptions.ProtoReflect.Descriptor instead.
func (*GraphqlMessageOptions) Descriptor() ([]byte, []int) {
	return file_graphql_proto_rawDescGZIP(), []int{3}
}

func (x *GraphqlMessageOptions) GetDelegateTo() string {
	if x != nil {
		return x.DelegateTo
	}
	return ""
}

type GraphqlOneofInterfaceOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields []string `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *GraphqlOneofInterfaceOptions) Reset() {
	*x = GraphqlOneofInterfaceOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphqlOneofInterfaceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphqlOneofInterfaceOptions) ProtoMessage() {}

func (x *GraphqlOneofInterfaceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphqlOneofInterfaceOptions.ProtoReflect.Descriptor instead.
func (*GraphqlOneofInterfaceOptions) Descriptor() ([]byte, []int) {
	return file_graphql_proto_rawDescGZIP(), []int{4}
}

func (x *GraphqlOneofInterfaceOptions) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

var file_graphql_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.MethodOptions)(nil),
		ExtensionType: (*GraphqlQueryOptions)(nil),
		Field:         2056,
		Name:          "protogql.graphql_query",
		Tag:           "bytes,2056,opt,name=graphql_query",
		Filename:      "graphql.proto",
	},
	{
		ExtendedType:  (*descriptor.MethodOptions)(nil),
		ExtensionType: (*GraphqlMutationOptions)(nil),
		Field:         2057,
		Name:          "protogql.graphql_mutation",
		Tag:           "bytes,2057,opt,name=graphql_mutation",
		Filename:      "graphql.proto",
	},
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*GraphqlFieldOptions)(nil),
		Field:         2056,
		Name:          "protogql.graphql_field",
		Tag:           "bytes,2056,opt,name=graphql_field",
		Filename:      "graphql.proto",
	},
	{
		ExtendedType:  (*descriptor.MessageOptions)(nil),
		ExtensionType: (*GraphqlMessageOptions)(nil),
		Field:         2056,
		Name:          "protogql.graphql_object",
		Tag:           "bytes,2056,opt,name=graphql_object",
		Filename:      "graphql.proto",
	},
	{
		ExtendedType:  (*descriptor.OneofOptions)(nil),
		ExtensionType: (*GraphqlOneofInterfaceOptions)(nil),
		Field:         2056,
		Name:          "protogql.graphql_interface",
		Tag:           "bytes,2056,opt,name=graphql_interface",
		Filename:      "graphql.proto",
	},
}

// Extension fields to descriptor.MethodOptions.
var (
	// optional protogql.GraphqlQueryOptions graphql_query = 2056;
	E_GraphqlQuery = &file_graphql_proto_extTypes[0]
	// optional protogql.GraphqlMutationOptions graphql_mutation = 2057;
	E_GraphqlMutation = &file_graphql_proto_extTypes[1]
)

// Extension fields to descriptor.FieldOptions.
var (
	// optional protogql.GraphqlFieldOptions graphql_field = 2056;
	E_GraphqlField = &file_graphql_proto_extTypes[2]
)

// Extension fields to descriptor.MessageOptions.
var (
	// optional protogql.GraphqlMessageOptions graphql_object = 2056;
	E_GraphqlObject = &file_graphql_proto_extTypes[3]
)

// Extension fields to descriptor.OneofOptions.
var (
	// optional protogql.GraphqlOneofInterfaceOptions graphql_interface = 2056;
	E_GraphqlInterface = &file_graphql_proto_extTypes[4]
)

var File_graphql_proto protoreflect.FileDescriptor

var file_graphql_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x72, 0x65, 0x6d, 0x69, 0x78, 0x65, 0x72, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x13, 0x47, 0x72,
	0x61, 0x70, 0x68, 0x71, 0x6c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x2c, 0x0a,
	0x16, 0x47, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x4d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x25, 0x0a, 0x13, 0x47,
	0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x38, 0x0a, 0x15, 0x47, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x64,
	0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x22, 0x36, 0x0a, 0x1c,
	0x47, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x3a, 0x62, 0x0a, 0x0d, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x5f,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x88, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72,
	0x65, 0x6d, 0x69, 0x78, 0x65, 0x72, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0c, 0x67, 0x72, 0x61, 0x70,
	0x68, 0x71, 0x6c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x3a, 0x6b, 0x0a, 0x10, 0x67, 0x72, 0x61, 0x70,
	0x68, 0x71, 0x6c, 0x5f, 0x6d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x89, 0x10, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x78, 0x65, 0x72, 0x2e, 0x47, 0x72,
	0x61, 0x70, 0x68, 0x71, 0x6c, 0x4d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x4d, 0x75, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x61, 0x0a, 0x0d, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c,
	0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x88, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72,
	0x65, 0x6d, 0x69, 0x78, 0x65, 0x72, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0c, 0x67, 0x72, 0x61, 0x70,
	0x68, 0x71, 0x6c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x3a, 0x67, 0x0a, 0x0e, 0x67, 0x72, 0x61, 0x70,
	0x68, 0x71, 0x6c, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x88, 0x10, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x78, 0x65, 0x72, 0x2e, 0x47, 0x72, 0x61,
	0x70, 0x68, 0x71, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x0d, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x3a, 0x72, 0x0a, 0x11, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x5f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x88, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x72,
	0x65, 0x6d, 0x69, 0x78, 0x65, 0x72, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x4f, 0x6e,
	0x65, 0x6f, 0x66, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x10, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x7a, 0x75, 0x6d, 0x69, 0x6e, 0x35, 0x32, 0x31, 0x30, 0x2f, 0x72,
	0x65, 0x6d, 0x69, 0x78, 0x65, 0x72, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_graphql_proto_rawDescOnce sync.Once
	file_graphql_proto_rawDescData = file_graphql_proto_rawDesc
)

func file_graphql_proto_rawDescGZIP() []byte {
	file_graphql_proto_rawDescOnce.Do(func() {
		file_graphql_proto_rawDescData = protoimpl.X.CompressGZIP(file_graphql_proto_rawDescData)
	})
	return file_graphql_proto_rawDescData
}

var file_graphql_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_graphql_proto_goTypes = []interface{}{
	(*GraphqlQueryOptions)(nil),          // 0: protogql.GraphqlQueryOptions
	(*GraphqlMutationOptions)(nil),       // 1: protogql.GraphqlMutationOptions
	(*GraphqlFieldOptions)(nil),          // 2: protogql.GraphqlFieldOptions
	(*GraphqlMessageOptions)(nil),        // 3: protogql.GraphqlMessageOptions
	(*GraphqlOneofInterfaceOptions)(nil), // 4: protogql.GraphqlOneofInterfaceOptions
	(*descriptor.MethodOptions)(nil),     // 5: google.protobuf.MethodOptions
	(*descriptor.FieldOptions)(nil),      // 6: google.protobuf.FieldOptions
	(*descriptor.MessageOptions)(nil),    // 7: google.protobuf.MessageOptions
	(*descriptor.OneofOptions)(nil),      // 8: google.protobuf.OneofOptions
}
var file_graphql_proto_depIdxs = []int32{
	5,  // 0: protogql.graphql_query:extendee -> google.protobuf.MethodOptions
	5,  // 1: protogql.graphql_mutation:extendee -> google.protobuf.MethodOptions
	6,  // 2: protogql.graphql_field:extendee -> google.protobuf.FieldOptions
	7,  // 3: protogql.graphql_object:extendee -> google.protobuf.MessageOptions
	8,  // 4: protogql.graphql_interface:extendee -> google.protobuf.OneofOptions
	0,  // 5: protogql.graphql_query:type_name -> protogql.GraphqlQueryOptions
	1,  // 6: protogql.graphql_mutation:type_name -> protogql.GraphqlMutationOptions
	2,  // 7: protogql.graphql_field:type_name -> protogql.GraphqlFieldOptions
	3,  // 8: protogql.graphql_object:type_name -> protogql.GraphqlMessageOptions
	4,  // 9: protogql.graphql_interface:type_name -> protogql.GraphqlOneofInterfaceOptions
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	5,  // [5:10] is the sub-list for extension type_name
	0,  // [0:5] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_graphql_proto_init() }
func file_graphql_proto_init() {
	if File_graphql_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_graphql_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphqlQueryOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphqlMutationOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphqlFieldOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphqlMessageOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphqlOneofInterfaceOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_graphql_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_graphql_proto_goTypes,
		DependencyIndexes: file_graphql_proto_depIdxs,
		MessageInfos:      file_graphql_proto_msgTypes,
		ExtensionInfos:    file_graphql_proto_extTypes,
	}.Build()
	File_graphql_proto = out.File
	file_graphql_proto_rawDesc = nil
	file_graphql_proto_goTypes = nil
	file_graphql_proto_depIdxs = nil
}
