// Code generated by protoc-gen-go. DO NOT EDIT.
// source: graphql.proto

package options

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GraphqlQueryOptions struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Output               string   `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphqlQueryOptions) Reset()         { *m = GraphqlQueryOptions{} }
func (m *GraphqlQueryOptions) String() string { return proto.CompactTextString(m) }
func (*GraphqlQueryOptions) ProtoMessage()    {}
func (*GraphqlQueryOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce0fc368bdc1a51, []int{0}
}

func (m *GraphqlQueryOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphqlQueryOptions.Unmarshal(m, b)
}
func (m *GraphqlQueryOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphqlQueryOptions.Marshal(b, m, deterministic)
}
func (m *GraphqlQueryOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphqlQueryOptions.Merge(m, src)
}
func (m *GraphqlQueryOptions) XXX_Size() int {
	return xxx_messageInfo_GraphqlQueryOptions.Size(m)
}
func (m *GraphqlQueryOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphqlQueryOptions.DiscardUnknown(m)
}

var xxx_messageInfo_GraphqlQueryOptions proto.InternalMessageInfo

func (m *GraphqlQueryOptions) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GraphqlQueryOptions) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type GraphqlMutationOptions struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphqlMutationOptions) Reset()         { *m = GraphqlMutationOptions{} }
func (m *GraphqlMutationOptions) String() string { return proto.CompactTextString(m) }
func (*GraphqlMutationOptions) ProtoMessage()    {}
func (*GraphqlMutationOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce0fc368bdc1a51, []int{1}
}

func (m *GraphqlMutationOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphqlMutationOptions.Unmarshal(m, b)
}
func (m *GraphqlMutationOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphqlMutationOptions.Marshal(b, m, deterministic)
}
func (m *GraphqlMutationOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphqlMutationOptions.Merge(m, src)
}
func (m *GraphqlMutationOptions) XXX_Size() int {
	return xxx_messageInfo_GraphqlMutationOptions.Size(m)
}
func (m *GraphqlMutationOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphqlMutationOptions.DiscardUnknown(m)
}

var xxx_messageInfo_GraphqlMutationOptions proto.InternalMessageInfo

func (m *GraphqlMutationOptions) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

var E_GraphqlQuery = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*GraphqlQueryOptions)(nil),
	Field:         2056,
	Name:          "remixer.graphql_query",
	Tag:           "bytes,2056,opt,name=graphql_query",
	Filename:      "graphql.proto",
}

var E_GraphqlMutation = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*GraphqlMutationOptions)(nil),
	Field:         2057,
	Name:          "remixer.graphql_mutation",
	Tag:           "bytes,2057,opt,name=graphql_mutation",
	Filename:      "graphql.proto",
}

func init() {
	proto.RegisterType((*GraphqlQueryOptions)(nil), "remixer.GraphqlQueryOptions")
	proto.RegisterType((*GraphqlMutationOptions)(nil), "remixer.GraphqlMutationOptions")
	proto.RegisterExtension(E_GraphqlQuery)
	proto.RegisterExtension(E_GraphqlMutation)
}

func init() {
	proto.RegisterFile("graphql.proto", fileDescriptor_3ce0fc368bdc1a51)
}

var fileDescriptor_3ce0fc368bdc1a51 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2f, 0x4a, 0x2c,
	0xc8, 0x28, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4a, 0xcd, 0xcd, 0xac,
	0x48, 0x2d, 0x92, 0x52, 0x48, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x0b, 0x27, 0x95, 0xa6,
	0xe9, 0xa7, 0xa4, 0x16, 0x27, 0x17, 0x65, 0x16, 0x94, 0xe4, 0x17, 0x41, 0x94, 0x2a, 0x39, 0x72,
	0x09, 0xbb, 0x43, 0xf4, 0x06, 0x96, 0xa6, 0x16, 0x55, 0xfa, 0x17, 0x94, 0x64, 0xe6, 0xe7, 0x15,
	0x0b, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81,
	0xd9, 0x42, 0x62, 0x5c, 0x6c, 0xf9, 0xa5, 0x25, 0x05, 0xa5, 0x25, 0x12, 0xcc, 0x60, 0x51, 0x28,
	0x4f, 0x49, 0x87, 0x4b, 0x0c, 0x6a, 0x84, 0x6f, 0x69, 0x49, 0x22, 0x48, 0x3f, 0x1e, 0x53, 0xac,
	0x92, 0xe0, 0x8e, 0x8d, 0x2f, 0x04, 0xd9, 0x28, 0x24, 0xa7, 0x07, 0x71, 0xa4, 0x1e, 0xcc, 0x91,
	0x7a, 0xbe, 0xa9, 0x25, 0x19, 0xf9, 0x29, 0x50, 0x43, 0x24, 0x3a, 0x04, 0x14, 0x18, 0x35, 0xb8,
	0x8d, 0x64, 0xf4, 0xa0, 0x9e, 0xd2, 0xc3, 0xe2, 0xde, 0x20, 0x9e, 0x74, 0x24, 0x41, 0xab, 0x6c,
	0x2e, 0x01, 0x98, 0x1d, 0xb9, 0x50, 0x27, 0x11, 0xb4, 0xa6, 0x13, 0x62, 0x8d, 0x3c, 0xba, 0x35,
	0x68, 0x7e, 0x0a, 0xe2, 0x4f, 0x47, 0x15, 0x77, 0x52, 0x8f, 0x52, 0x4d, 0xcf, 0x2c, 0xc9, 0x28,
	0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0xac, 0x2a, 0xcd, 0xcd, 0xcc, 0x33, 0x35, 0x32, 0x34,
	0xd0, 0x87, 0x1a, 0xa4, 0x9f, 0x0f, 0xd1, 0x99, 0xc4, 0x06, 0xb6, 0xd9, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x9b, 0x69, 0x3c, 0xce, 0xad, 0x01, 0x00, 0x00,
}
