// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package resolver

import (
	"context"
	"testapp/model"
)

func (a *queryProtoResolverAdapter) Hello(ctx context.Context) ([]*model.Hello, error) {
	resp, err := a.protoResolver.Hello(ctx)
	if err != nil {
		return nil, err
	}
	return model.HelloListFromRepeatedProto(resp), nil
}

type queryProtoResolverAdapter struct{ protoResolver *queryProtoResolver }

