// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: extensions/schema.proto

package extensions_pb

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/izumin5210/protogql/protobuf/protogql"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PrefixedEnum int32

const (
	PrefixedEnum_PREFIXED_ENUM_UNSPECIFIED PrefixedEnum = 0
	PrefixedEnum_PREFIXED_FOO              PrefixedEnum = 1
	PrefixedEnum_PREFIXED_BAR              PrefixedEnum = 2
)

// Enum value maps for PrefixedEnum.
var (
	PrefixedEnum_name = map[int32]string{
		0: "PREFIXED_ENUM_UNSPECIFIED",
		1: "PREFIXED_FOO",
		2: "PREFIXED_BAR",
	}
	PrefixedEnum_value = map[string]int32{
		"PREFIXED_ENUM_UNSPECIFIED": 0,
		"PREFIXED_FOO":              1,
		"PREFIXED_BAR":              2,
	}
)

func (x PrefixedEnum) Enum() *PrefixedEnum {
	p := new(PrefixedEnum)
	*p = x
	return p
}

func (x PrefixedEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrefixedEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_extensions_schema_proto_enumTypes[0].Descriptor()
}

func (PrefixedEnum) Type() protoreflect.EnumType {
	return &file_extensions_schema_proto_enumTypes[0]
}

func (x PrefixedEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrefixedEnum.Descriptor instead.
func (PrefixedEnum) EnumDescriptor() ([]byte, []int) {
	return file_extensions_schema_proto_rawDescGZIP(), []int{0}
}

type PrefixedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *PrefixedMessage) Reset() {
	*x = PrefixedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extensions_schema_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrefixedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixedMessage) ProtoMessage() {}

func (x *PrefixedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_schema_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixedMessage.ProtoReflect.Descriptor instead.
func (*PrefixedMessage) Descriptor() ([]byte, []int) {
	return file_extensions_schema_proto_rawDescGZIP(), []int{0}
}

func (x *PrefixedMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type PrefixedMessage_InnerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *PrefixedMessage_InnerMessage) Reset() {
	*x = PrefixedMessage_InnerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extensions_schema_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrefixedMessage_InnerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixedMessage_InnerMessage) ProtoMessage() {}

func (x *PrefixedMessage_InnerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_schema_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixedMessage_InnerMessage.ProtoReflect.Descriptor instead.
func (*PrefixedMessage_InnerMessage) Descriptor() ([]byte, []int) {
	return file_extensions_schema_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PrefixedMessage_InnerMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_extensions_schema_proto protoreflect.FileDescriptor

var file_extensions_schema_proto_rawDesc = []byte{
	0x0a, 0x17, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x74, 0x65, 0x73, 0x74, 0x61,
	0x70, 0x69, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x16, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x67, 0x71, 0x6c, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a, 0x0f, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x65,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x1a, 0x22, 0x0a, 0x0c,
	0x49, 0x6e, 0x6e, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x2a, 0x51, 0x0a, 0x0c, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x65, 0x64, 0x45, 0x6e, 0x75, 0x6d,
	0x12, 0x1d, 0x0a, 0x19, 0x50, 0x52, 0x45, 0x46, 0x49, 0x58, 0x45, 0x44, 0x5f, 0x45, 0x4e, 0x55,
	0x4d, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x10, 0x0a, 0x0c, 0x50, 0x52, 0x45, 0x46, 0x49, 0x58, 0x45, 0x44, 0x5f, 0x46, 0x4f, 0x4f, 0x10,
	0x01, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x52, 0x45, 0x46, 0x49, 0x58, 0x45, 0x44, 0x5f, 0x42, 0x41,
	0x52, 0x10, 0x02, 0x42, 0x32, 0x5a, 0x20, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x65,
	0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x3b, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x62, 0xc2, 0x80, 0x01, 0x0c, 0x0a, 0x0a, 0x54, 0x65, 0x73,
	0x74, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_extensions_schema_proto_rawDescOnce sync.Once
	file_extensions_schema_proto_rawDescData = file_extensions_schema_proto_rawDesc
)

func file_extensions_schema_proto_rawDescGZIP() []byte {
	file_extensions_schema_proto_rawDescOnce.Do(func() {
		file_extensions_schema_proto_rawDescData = protoimpl.X.CompressGZIP(file_extensions_schema_proto_rawDescData)
	})
	return file_extensions_schema_proto_rawDescData
}

var file_extensions_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_extensions_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_extensions_schema_proto_goTypes = []interface{}{
	(PrefixedEnum)(0),                    // 0: testapi.extensions.PrefixedEnum
	(*PrefixedMessage)(nil),              // 1: testapi.extensions.PrefixedMessage
	(*PrefixedMessage_InnerMessage)(nil), // 2: testapi.extensions.PrefixedMessage.InnerMessage
}
var file_extensions_schema_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_extensions_schema_proto_init() }
func file_extensions_schema_proto_init() {
	if File_extensions_schema_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_extensions_schema_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrefixedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extensions_schema_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrefixedMessage_InnerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_extensions_schema_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extensions_schema_proto_goTypes,
		DependencyIndexes: file_extensions_schema_proto_depIdxs,
		EnumInfos:         file_extensions_schema_proto_enumTypes,
		MessageInfos:      file_extensions_schema_proto_msgTypes,
	}.Build()
	File_extensions_schema_proto = out.File
	file_extensions_schema_proto_rawDesc = nil
	file_extensions_schema_proto_goTypes = nil
	file_extensions_schema_proto_depIdxs = nil
}
