// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package graph

import (
	"context"
	"todoapp/graph/resolver"
)

// Injectors from wire.go:

func NewApp(contextContext context.Context) (*App, func(), error) {
	taskServiceClient, cleanup, err := provideTaskClient()
	if err != nil {
		return nil, nil, err
	}
	resolverResolver := &resolver.Resolver{
		TaskClient: taskServiceClient,
	}
	app := &App{
		Resolver: resolverResolver,
	}
	return app, func() {
		cleanup()
	}, nil
}
