name: CI

on: [push, pull_request]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: |
        go mod download

    - name: Test
      run: |
        go test -v -race \
          -coverpkg $(go list ./... | grep -E -v 'github.com/izumin5210/protogql/gqlgentest' | paste -s -d,) \
          -coverprofile coverage.out \
          -covermode atomic \
          ./...

    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1.0.7
      with:
        infile: coverage.out
        outfile: coverage.lcov

    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov

  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: |
        go mod download
      working-directory: ./e2e

    - name: E2E test
      run: |
        go test -v -race ./...
      working-directory: ./e2e
